START TRANSACTION;

CREATE TABLE aerialphotos (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    geometry geometry(point) NOT NULL,
    name character varying(40) NOT NULL,
    date timestamp without time zone NOT NULL,
    surveyid bigint NOT NULL,
    usercreation text NOT NULL,
    creation timestamp without time zone NOT NULL,
    usermodification text NULL,
    modification timestamp without time zone NULL,
    CONSTRAINT pk_aerialphotos PRIMARY KEY (id),
    CONSTRAINT fk_aerialphotos_surveys_surveyid FOREIGN KEY (surveyid) REFERENCES surveys (id) ON DELETE RESTRICT
);

CREATE INDEX ix_aerialphotos_surveyid ON aerialphotos (surveyid);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20210418133409_AerialPhotos', '5.0.2');

COMMIT;

START TRANSACTION;

create index aerialphotos_geom_idx on aerialphotos using gist(geometry)

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20210418134434_AerialPhotosSpatial', '5.0.2');

COMMIT;

